---
- hosts: testserver
  sudo: yes

  tasks:

  - name: Add repository
    apt_repository: repo='ppa:webupd8team/java'

  - name: Udpate repositories
    apt: upgrade=dist

  - name: Accept Java 8 License
    sudo: yes
    debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

  - name: Install packages
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - git
      - maven
      - oracle-java8-installer

  - name: Git clone vertx demo
    git: repo=https://github.com/marti1125/VertxVerticle.git dest=VertxVerticle/

  - name: cd VertxVerticle
    command: chdir=/home/vagrant/VertxVerticle ls
    register: insidedir

  - debug: msg="{{ insidedir.stdout }}"

  - debug: msg="{{ insidedir.stderr }}"

  - command: mvn -f VertxVerticle/pom.xml clean package

  - command: java -jar VertxVerticle/target/maven-verticle-3.2.1-fat.jar
